on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/setup-python@v6.2.0
        with:
          python-version: "pypy3.10"

      - uses: actions/setup-node@v6.4.0
        with:
          node-version: "24"

      - run: |
          sudo apt-get update
          sudo apt-get -y install build-essential gcc g++ gcc-multilib g++-multilib wget zip tar binutils binutils-i686-linux-gnu lld

          git clone https://github.com/greenheartgames/greenworks greenworks

          wget https://github.com/teodorjuravlea/crosscode-greenworks/raw/refs/heads/master/steamworks_sdk_162.zip
          unzip steamworks_sdk_162.zip -d greenworks/deps
          mv greenworks/deps/sdk greenworks/deps/steamworks_sdk

          cd greenworks
          git checkout v0.22.0

          npm install node-gyp nan

          mkdir --parents release/assets/modules/greenworks-nw-0.35

          npx node-gyp configure --target=0.112.0 --arch=x64 --disturl=https://dl.nwjs.io/
          npx node-gyp build --target=0.112.0 --arch=x64 --disturl=https://dl.nwjs.io/
          mv lib release/assets/modules/greenworks-nw-0.35/linux64

          npx node-gyp configure --target=0.112.0 --arch=ia32 --disturl=https://dl.nwjs.io/
          CFLAGS="-fPIC" CXXFLAGS="-fPIC" npx node-gyp build --target=0.112.0 --arch=ia32 --disturl=https://dl.nwjs.io/
          mv lib release/assets/modules/greenworks-nw-0.35/linux32

          cd release
          zip -r crosscode-v1.4.2-3-nwjs-v0.112.0-gw-v0.22.0-sw-v1.62.zip assets

      - uses: softprops/action-gh-release@v3
        with:
          files: |
            greenworks/release/crosscode-v1.4.2-3-nwjs-v0.112.0-gw-v0.22.0-sw-v1.62.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
